//Kevin Luiz Botelho Lima - RA: 2266423
//Desenvolvido com o Apache Netbeans IDE 24

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.awt.event.*;
import javax.swing.JOptionPane;

public class FormPrincipal extends javax.swing.JFrame {
    private GerCliente gc = GerCliente.geraGerCliente();
    public static AcoesPetrobras acoesPetrobras = new AcoesPetrobras();
    public static LocalDate hoje = LocalDate.now();
    
    public FormPrincipal() {
        initComponents();

        // Listener para verificar quando a aplicação iniciar
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                // Armazenará a data do computador quando a aplicação iniciar
                atualizaData();
            }
        });
    }

    //Metodo para armazenar na aplicação a data do computador do usuário
    public void atualizaData(){
        labelData.setText(hoje.format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
    }
    
    //Metodo para avançar 1 mês na data, de modo a simular o funcionamento do rendimento
    //de uma conta poupança com o passar do tempo e a valorização de ações para a conta de investimentos
    public void avancaData(){
        hoje = hoje.plusMonths(1);
        atualizaData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelTxtData = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        buttonCadastro = new javax.swing.JButton();
        buttonConsulta = new javax.swing.JButton();
        buttonAlteraData = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRelatorio = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTitulo.setText("Simulador Bancário");

        labelTxtData.setText("Data atual:");

        labelData.setText("LabelData");

        buttonCadastro.setText("Cadastrar novo cliente");
        buttonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastroActionPerformed(evt);
            }
        });

        buttonConsulta.setText("Consultar cadastro pelo CPF");
        buttonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConsultaActionPerformed(evt);
            }
        });

        buttonAlteraData.setText("Avançar 1 mês");
        buttonAlteraData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlteraDataActionPerformed(evt);
            }
        });

        menuRelatorio.setText("Relatório");

        jMenuItem1.setText("Relatório de clientes cadastrados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuRelatorio.add(jMenuItem1);

        jMenuBar1.add(menuRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTitulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelTxtData)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(labelData))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonConsulta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonCadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAlteraData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTxtData)
                    .addComponent(labelData))
                .addGap(35, 35, 35)
                .addComponent(buttonCadastro)
                .addGap(18, 18, 18)
                .addComponent(buttonConsulta)
                .addGap(18, 18, 18)
                .addComponent(buttonAlteraData)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastroActionPerformed
        abreCadCliente();
    }//GEN-LAST:event_buttonCadastroActionPerformed

    private void buttonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConsultaActionPerformed
        abreConsultaCliente();
    }//GEN-LAST:event_buttonConsultaActionPerformed

    private void buttonAlteraDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlteraDataActionPerformed
        avancaData();
        gc.atualizaSaldos();
    }//GEN-LAST:event_buttonAlteraDataActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        abreRelClientesCadastrados();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    //Metodo que chama a abertura do relatório de cadastros de clientes
    public void abreRelClientesCadastrados(){
        RelClientesCadastrados.geraRelClientesCadastrados().setVisible(true);
    }
    
    //Metodo que chama a abertura do formulario de cadastro de cliente
    public void abreCadCliente(){
        FormCadCliente.geraCadCliente().setVisible(true);
    }
    
    //Metodo que chama a abertura do formulario de consulta com o CPF
    public void abreConsultaCliente(){
        FormConsultaCliente.geraConsultaCliente().setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAlteraData;
    private javax.swing.JButton buttonCadastro;
    private javax.swing.JButton buttonConsulta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTxtData;
    private javax.swing.JMenu menuRelatorio;
    // End of variables declaration//GEN-END:variables
}
