//Kevin Luiz Botelho Lima - RA: 2266423

import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;


public class FormVisualizarCorrente extends javax.swing.JFrame {
    private GerCliente gc = GerCliente.geraGerCliente();
    private Cliente c1 = new Cliente();
    private static FormVisualizarCorrente visualizaCorrenteUnic; // 1º passo singleton
    
    private FormVisualizarCorrente() { // 2º passo singleton
        initComponents();
    }
    
    public static FormVisualizarCorrente geraVisualizaCorrente(Cliente c1){ //3º passo singleton
        if(visualizaCorrenteUnic == null){
                visualizaCorrenteUnic = new FormVisualizarCorrente();
            }
            
            visualizaCorrenteUnic.atualizaC1(c1);
            return visualizaCorrenteUnic;
    }
    
    public void atualizaC1(Cliente c1){
        this.c1 = c1;
        preencherCampos();
    }
    
    //Metodo para informar na tela as informações da conta corrente selecionada
    private void preencherCampos(){
        
        labelDadoCpf.setText(String.valueOf(c1.getCpf()));
        labelDadoNome.setText(c1.getNome());
        labelDadoNConta.setText(String.valueOf(c1.getContaCorrente().getNumeroConta()));
        labelDadoAgencia.setText(String.valueOf(c1.getContaCorrente().getAgencia()));
        labelDadoDataAbertura.setText(c1.getContaCorrente().getDataAbertura().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        labelDadoLimiteChequeEsp.setText(String.format("%.2f", c1.getContaCorrente().getLimiteChequeEspecial()));
        labelDadoSaldo.setText(String.format("%.2f", c1.getContaCorrente().getSaldo()));
        
    }
    
    //Metodo para a realização de deposito na conta corrente
    public void depositar(){
        boolean depositoValido = true;
        
        while(depositoValido){
            Double deposito = Double.valueOf(JOptionPane.showInputDialog(
                                    null,
                                    "Informe o valor a ser depositado: ",
                                    "Deposito em conta corrente",
                                    JOptionPane.INFORMATION_MESSAGE
                            ));
            
            if(deposito > 0){
                c1.getContaCorrente().depositar(deposito);
                depositoValido = false;
            }else{
                JOptionPane.showMessageDialog(
                        null,
                        "O valor do deposito deve ser maior que R$ 0,00",
                        "Erro na entrada de dados",
                        JOptionPane.ERROR_MESSAGE
                    );
            }
            
            
            //Atualiza o cadastro do cliente em questão no array list
        c1 = gc.atualizaClienteCpf(c1);

            if(c1 != null){
                JOptionPane.showMessageDialog(
                        null,
                        "Deposito realizado com sucesso!",
                        "Deposito em conta corrente",
                        JOptionPane.INFORMATION_MESSAGE
                );
                preencherCampos();
            }
        }  
    }
    
    
     //Metodo para a realização de saque na conta corrente
    public void sacar(){
        try{
            Double saque = Double.valueOf(JOptionPane.showInputDialog(
                                    null,
                                    "Informe o valor de saque: ",
                                    "Saque em conta corrente",
                                    JOptionPane.INFORMATION_MESSAGE
                            ));
            
            c1.getContaCorrente().sacar(saque);
            
            //Atualiza o cadastro do cliente em questão no array list
            c1 = gc.atualizaClienteCpf(c1);

            if(c1 != null){
                JOptionPane.showMessageDialog(
                        null,
                        "Saque realizado com sucesso!",
                        "Saque em conta corrente",
                        JOptionPane.INFORMATION_MESSAGE
                );
                preencherCampos();
            }
        }
        catch (SemSaldoException sse){
            JOptionPane.showMessageDialog(
                        null,
                        sse.impErrSaldo(),
                        "Saque em conta corrente",
                        JOptionPane.INFORMATION_MESSAGE
                );
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        labelDadoCpf = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelDadoNome = new javax.swing.JLabel();
        labelNConta = new javax.swing.JLabel();
        labelDadoNConta = new javax.swing.JLabel();
        labelAgencia = new javax.swing.JLabel();
        labelDadoAgencia = new javax.swing.JLabel();
        labelDataAbertura = new javax.swing.JLabel();
        labelDadoDataAbertura = new javax.swing.JLabel();
        labelLimiteChequeEsp = new javax.swing.JLabel();
        labelDadoLimiteChequeEsp = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        labelDadoSaldo = new javax.swing.JLabel();
        buttonDepositar = new javax.swing.JButton();
        buttonSacar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTitulo.setText("Visualizacao de Conta Corrente");

        labelCpf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelCpf.setText("CPF:");
        labelCpf.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                labelCpfComponentHidden(evt);
            }
        });

        labelDadoCpf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDadoCpf.setText("Default");

        labelNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNome.setText("Nome:");

        labelDadoNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDadoNome.setText("Default");

        labelNConta.setText("Numero da conta:");

        labelDadoNConta.setText("Default");

        labelAgencia.setText("Agencia:");

        labelDadoAgencia.setText("Default");

        labelDataAbertura.setText("Data de abertura:");

        labelDadoDataAbertura.setText("Default");

        labelLimiteChequeEsp.setText("Limite do cheque especial:");

        labelDadoLimiteChequeEsp.setText("Default");

        labelSaldo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSaldo.setText("Saldo (R$):");

        labelDadoSaldo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelDadoSaldo.setText("Default");

        buttonDepositar.setText("Depositar");
        buttonDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDepositarActionPerformed(evt);
            }
        });

        buttonSacar.setText("Sacar");
        buttonSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSacarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNome)
                                    .addComponent(labelCpf))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDadoNome)
                                    .addComponent(labelDadoCpf))
                                .addGap(297, 297, 297))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonSacar)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelNConta)
                                                .addComponent(labelAgencia)
                                                .addComponent(labelDataAbertura))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelDadoNConta)
                                                .addComponent(labelDadoDataAbertura)
                                                .addComponent(labelDadoAgencia)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelLimiteChequeEsp)
                                            .addGap(18, 18, 18)
                                            .addComponent(labelDadoLimiteChequeEsp))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelSaldo)
                                            .addGap(18, 18, 18)
                                            .addComponent(labelDadoSaldo))))
                                .addGap(61, 61, 61))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonDepositar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpf)
                    .addComponent(labelDadoCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(labelDadoNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNConta)
                    .addComponent(labelDadoNConta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAgencia)
                    .addComponent(labelDadoAgencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataAbertura)
                    .addComponent(labelDadoDataAbertura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLimiteChequeEsp)
                    .addComponent(labelDadoLimiteChequeEsp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSaldo)
                    .addComponent(labelDadoSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDepositar)
                    .addComponent(buttonSacar))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelCpfComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_labelCpfComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_labelCpfComponentHidden

    private void buttonDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDepositarActionPerformed
        depositar();
    }//GEN-LAST:event_buttonDepositarActionPerformed

    private void buttonSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSacarActionPerformed
        sacar();
    }//GEN-LAST:event_buttonSacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVisualizarCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVisualizarCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVisualizarCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVisualizarCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVisualizarCorrente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDepositar;
    private javax.swing.JButton buttonSacar;
    private javax.swing.JLabel labelAgencia;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelDadoAgencia;
    private javax.swing.JLabel labelDadoCpf;
    private javax.swing.JLabel labelDadoDataAbertura;
    private javax.swing.JLabel labelDadoLimiteChequeEsp;
    private javax.swing.JLabel labelDadoNConta;
    private javax.swing.JLabel labelDadoNome;
    private javax.swing.JLabel labelDadoSaldo;
    private javax.swing.JLabel labelDataAbertura;
    private javax.swing.JLabel labelLimiteChequeEsp;
    private javax.swing.JLabel labelNConta;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
