//Kevin Luiz Botelho Lima - RA: 2266423

import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;

public class RelClientesCadastrados extends javax.swing.JFrame {
    private GerCliente gc = GerCliente.geraGerCliente();
    private Cliente c1 = new Cliente();
    
    private static RelClientesCadastrados clientesCadastradosUnic; // 1º passo singleton
    
    private RelClientesCadastrados() { // 2º passo singleton
        initComponents();
    }
    
    public static RelClientesCadastrados geraRelClientesCadastrados(){ //3º passo singleton
        if(clientesCadastradosUnic == null){
                clientesCadastradosUnic = new RelClientesCadastrados();
            }

            return clientesCadastradosUnic;
    }
    
    public void lisTab(){
        String cc, cp, ci;
        DefaultTableModel modTab = (DefaultTableModel) tableRelClientesCadastrados.getModel();
        
        int posLin = 0;
        
        modTab.setRowCount(posLin);
        
        for(Cliente c : gc.getBdCliente()){ //for each
            
            //Sequencia de condicionais para verificar se o cliente possui alguma conta criada
            //as variaveis cc, cp, e ci do tipo String armazenarão sim ou não para apresentar no relatório
            //quais contas o cliente possui
            if(c.getContaCorrente() == null){
                cc = "Não";
            }else{
                cc = "Sim";
            }

            if(c.getContaPoupanca() == null){
                cp = "Não";
            }else{
                cp = "Sim";
            }

            if(c.getContaInvestimento() == null){
                ci = "Não";
            }else{
                ci = "Sim";
            }
            
            modTab.insertRow(posLin, new Object[]{c.getCpf(), c.getNome(), c.getDataNascimento().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")), c.getSexo(), c.getCelular(), cc, cp, ci});
            posLin++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRelClientesCadastrados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTitulo.setText("Relatório de clientes cadastrados");

        tableRelClientesCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Data Nascimento", "Sexo", "Celular", "Conta Corrente?", "Conta Poupança?", "Conta Investimento?"
            }
        ));
        jScrollPane1.setViewportView(tableRelClientesCadastrados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        setBounds(0, 0, 956, 509);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lisTab();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelClientesCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelClientesCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelClientesCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelClientesCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelClientesCadastrados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTable tableRelClientesCadastrados;
    // End of variables declaration//GEN-END:variables
}
